name: Meal planner via Email (fast with cache)

# Workflow otimizado com cache de dependências (pip) e cache da
# lista de receitas. Agendado semanalmente aos domingos às 11:00 UTC
# (08:00 horário de São Paulo).
on:
  schedule:
    - cron: '0 11 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MEAL_PLANNER_EMAIL: ${{ secrets.MEAL_PLANNER_EMAIL }}
      MEAL_PLANNER_PASS: ${{ secrets.MEAL_PLANNER_PASS }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      # Cache da lista de receitas (restaura se existir)
      - name: Restaurar cache de receitas
        uses: actions/cache@v3
        with:
          path: receitas_cache.json
          key: receitas-cache

      - uses: actions/checkout@v3

      # Configura Python com cache de dependências pip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4 schedule

      - name: Executar o agente
        run: python meal_planner_email_fast.py

      # Salva o cache atualizado de receitas para próximas execuções
      - name: Salvar cache de receitas
        uses: actions/cache@v3
        with:
          path: receitas_cache.json
          key: receitas-cache
